"""init schema

Revision ID: 231db57b5b6f
Revises: 
Create Date: 2026-08-19 21:46:57.762478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '231db57b5b6f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('contact_person', sa.String(length=64), nullable=True),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_wechat', sa.String(length=64), nullable=True),
    sa.Column('booking_email', sa.String(length=255), nullable=True),
    sa.Column('cc_emails', sa.JSON(), nullable=False),
    sa.Column('service_routes', sa.JSON(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_name'), ['name'], unique=False)

    op.create_table('email_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('template_code', sa.String(length=64), nullable=True),
    sa.Column('to_emails', sa.JSON(), nullable=False),
    sa.Column('cc_emails', sa.JSON(), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'RETRYING', name='emailstatus'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=True),
    sa.Column('so_id', sa.String(length=36), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_logs_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_logs_so_id'), ['so_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_logs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_logs_template_code'), ['template_code'], unique=False)

    op.create_table('email_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_templates_code'), ['code'], unique=True)

    op.create_table('bookings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_no', sa.String(length=64), nullable=False),
    sa.Column('carrier', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('pol', sa.String(length=64), nullable=False),
    sa.Column('pod', sa.String(length=64), nullable=False),
    sa.Column('etd', sa.DateTime(), nullable=True),
    sa.Column('eta', sa.DateTime(), nullable=True),
    sa.Column('cut_off', sa.DateTime(), nullable=True),
    sa.Column('container_type', sa.String(length=16), nullable=False),
    sa.Column('container_count', sa.Integer(), nullable=False),
    sa.Column('commodity', sa.Text(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('volume_cbm', sa.Float(), nullable=True),
    sa.Column('customer_name', sa.String(length=255), nullable=True),
    sa.Column('customer_ref', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'CONFIRMED', 'REJECTED', 'CANCELLED', 'COMPLETED', name='bookingstatus'), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_booking_no'), ['booking_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_bookings_carrier'), ['carrier'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_pod'), ['pod'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_pol'), ['pol'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_status'), ['status'], unique=False)

    op.create_table('bills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('bill_no', sa.String(length=64), nullable=False),
    sa.Column('bill_type', sa.String(length=16), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('line_items', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'OCR_DONE', 'OCR_FAILED', 'CONFIRMED', 'DISPUTED', 'PAID', name='billstatus'), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bills_bill_no'), ['bill_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_bills_status'), ['status'], unique=False)

    op.create_table('sos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_email', sa.String(length=255), nullable=True),
    sa.Column('source_subject', sa.String(length=500), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_mime', sa.String(length=128), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'OCR_DONE', 'OCR_FAILED', 'CONFIRMED', 'REJECTED', name='sostatus'), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('ocr_engine', sa.String(length=32), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('ocr_error', sa.Text(), nullable=True),
    sa.Column('ocr_at', sa.DateTime(), nullable=True),
    sa.Column('carrier', sa.String(length=64), nullable=True),
    sa.Column('so_number', sa.String(length=64), nullable=True),
    sa.Column('bl_number', sa.String(length=64), nullable=True),
    sa.Column('booking_number', sa.String(length=64), nullable=True),
    sa.Column('vessel_name', sa.String(length=128), nullable=True),
    sa.Column('voyage_no', sa.String(length=32), nullable=True),
    sa.Column('pol', sa.String(length=64), nullable=True),
    sa.Column('pod', sa.String(length=64), nullable=True),
    sa.Column('etd', sa.DateTime(), nullable=True),
    sa.Column('eta', sa.DateTime(), nullable=True),
    sa.Column('cut_off', sa.DateTime(), nullable=True),
    sa.Column('container_type', sa.String(length=16), nullable=True),
    sa.Column('container_count', sa.Integer(), nullable=True),
    sa.Column('shipper', sa.String(length=255), nullable=True),
    sa.Column('consignee', sa.String(length=255), nullable=True),
    sa.Column('notify_party', sa.String(length=255), nullable=True),
    sa.Column('commodity', sa.Text(), nullable=True),
    sa.Column('extra_fields', sa.JSON(), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sos_carrier'), ['carrier'], unique=False)
        batch_op.create_index(batch_op.f('ix_sos_pod'), ['pod'], unique=False)
        batch_op.create_index(batch_op.f('ix_sos_pol'), ['pol'], unique=False)
        batch_op.create_index(batch_op.f('ix_sos_so_number'), ['so_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_sos_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_sos_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sos_status'))
        batch_op.drop_index(batch_op.f('ix_sos_source'))
        batch_op.drop_index(batch_op.f('ix_sos_so_number'))
        batch_op.drop_index(batch_op.f('ix_sos_pol'))
        batch_op.drop_index(batch_op.f('ix_sos_pod'))
        batch_op.drop_index(batch_op.f('ix_sos_carrier'))

    op.drop_table('sos')
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bills_status'))
        batch_op.drop_index(batch_op.f('ix_bills_bill_no'))

    op.drop_table('bills')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_status'))
        batch_op.drop_index(batch_op.f('ix_bookings_pol'))
        batch_op.drop_index(batch_op.f('ix_bookings_pod'))
        batch_op.drop_index(batch_op.f('ix_bookings_carrier'))
        batch_op.drop_index(batch_op.f('ix_bookings_booking_no'))

    op.drop_table('bookings')
    with op.batch_alter_table('email_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_templates_code'))

    op.drop_table('email_templates')
    with op.batch_alter_table('email_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_logs_template_code'))
        batch_op.drop_index(batch_op.f('ix_email_logs_status'))
        batch_op.drop_index(batch_op.f('ix_email_logs_so_id'))
        batch_op.drop_index(batch_op.f('ix_email_logs_booking_id'))

    op.drop_table('email_logs')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_name'))

    op.drop_table('agents')
    # ### end Alembic commands ###
